In [1]:
3.1
import numpy as np
import copy

n = 7
N = 6
A = np.array([[3 / ((0.1 * N * i * j)**4-4 * (0.1 * N *i*j)**3) for j in range (1, n + 1)] for i in range (1, n + 1) ])

b = np.ones(n) * N

print ("A: \n",A)
print ("b: \n",b)

x = np.linalg.solve(A, b)
print ('Решение системы Ax = b: \n', x)

#число обусловленности матрицы
cond_A = np.linalg.cond(A)
print ('Число обусловленности матрицы A:', cond_A)

eps = 0.001
d = np.zeros(n)

for i in range(n):
    b_k = copy.copy(b)
    b_k[i] += eps
    x_i = np.linalg.solve(A,b_k)
    d[i] = np.linalg.norm(x - x_i, np.inf) / np.linalg.norm(x, np.inf)

print ("Вектор относительных погрешностей решений: ")
print(d.reshape(7,1))  
print ("\nИндекс компоненты, оказывающая наибольшее влиянее на погрешность решения:", np.argmax(d))

#теоретическая погрешность решения
cond_A * np.linalg.norm(b - b_k, np.inf) / np.linalg.norm(b, np.inf)

A: 
 [[-4.08496732e+00 -6.20039683e-01 -2.33819678e-01 -1.35633681e-01
  -1.11111111e-01 -1.60751029e-01  2.02461937e-01]
 [-6.20039683e-01 -1.35633681e-01 -1.60751029e-01  3.39084201e-02
   6.94444444e-03  2.51173483e-03  1.15035192e-03]
 [-2.33819678e-01 -1.60751029e-01  1.36085527e-02  2.51173483e-03
   8.23045267e-04  3.50220106e-04  1.74385820e-04]
 [-1.35633681e-01  3.39084201e-02  2.51173483e-03  6.05507502e-04
   2.17013889e-04  9.66051856e-05  4.94291839e-05]
 [-1.11111111e-01  6.94444444e-03  8.23045267e-04  2.17013889e-04
   8.08080808e-05  3.67430923e-05  1.90552411e-05]
 [-1.60751029e-01  2.51173483e-03  3.50220106e-04  9.66051856e-05
   3.67430923e-05  1.69140392e-05  8.84267720e-06]
 [ 2.02461937e-01  1.15035192e-03  1.74385820e-04  4.94291839e-05
   1.90552411e-05  8.84267720e-06  4.64777983e-06]]
b: 
 [6. 6. 6. 6. 6. 6. 6.]
Решение системы Ax = b: 
 [ 4.22830736e+00  8.63582825e+02  1.16140840e+05  5.36275970e+06
 -5.13172315e+07  6.46491798e+07  2.68968736e+07]
Число 

19931.21991239135

In [37]:
3.2
n=100
b = np.array([4.0] * n)
# Матрица А симметричная, найдем ее собственные значения и собственные векторы:
A_eigenvalues, A_eigenvectors = np.linalg.eigh(A)
print('Собственные значения:\n\n', A_eigenvalues)
print('\nСобственные векторы:\n\n', A_eigenvectors)
# Немного изменим матрицу А (получим возмущенную матрицу А)
a = 1.002
A_eps = A * a
print(A_eps)
# Найдем решения с новой матрицей А
x_epsilon = np.linalg.solve(A_eps, b)
print('Решения системы с возмущенной матрицей A:\n\n', x_epsilon)
# Оценка погрешности
condA * np.linalg.norm(A_eps - A, ord=np.inf) / np.linalg.norm(A, ord=np.inf)

Собственные значения:

 [-6.79520946e-03 -1.12813254e-05 -4.11624052e-10 -9.51717899e-16
 -1.28441573e-21 -3.14315879e-22 -8.37808165e-23 -3.64916186e-23
 -2.91572302e-23 -1.81782173e-23 -9.16458495e-24 -8.92872487e-24
 -5.25181015e-24 -3.01440000e-24 -2.23565766e-24 -1.70549187e-24
 -1.09880253e-24 -7.09849239e-25 -5.14607153e-25 -3.60194535e-25
 -3.18084836e-25 -2.30167945e-25 -1.65123015e-25 -1.45950134e-25
 -1.22834618e-25 -1.13651636e-25 -1.00977232e-25 -7.30613399e-26
 -4.34325220e-26 -4.16087162e-26 -3.53600101e-26 -2.88706507e-26
 -2.62347834e-26 -1.92980062e-26 -1.59958453e-26 -1.49358618e-26
 -1.24418327e-26 -9.65759725e-27 -7.57640783e-27 -6.32354596e-27
 -5.68503726e-27 -5.23071676e-27 -4.02425013e-27 -3.57799677e-27
 -3.27219323e-27 -2.09528461e-27 -1.46760578e-27 -8.59832834e-28
 -5.29652148e-28 -5.17857970e-28 -1.45986856e-28  1.98274414e-28
  7.22446672e-28  9.34035679e-28  1.24433009e-27  2.45553226e-27
  2.95659613e-27  3.41618062e-27  4.38164774e-27  4.65671223e-27
 

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 100 is different from 99)

In [20]:
3.3
import numpy as np
from numpy.linalg import solve, cond, norm
import copy

A = np.array([[3, 1, 0, 0, 0],
              [1, 2, 1, 0, 0],
              [0, 1, 1, 1, 0],
              [0, 0, 1, 0, 1],
              [0, 0, 0, 1, 1]], dtype=np.float32).reshape(5, 5)

def b_set_func(i, n=5):
    temp = np.array([0]*n)
    temp[i] = np.random.randint(100)+1
    print(temp)
    return temp

k=5
b_set = [b_set_func(i) for i in range(k)]
x_set = [solve(A, b_set[i]) for i in range(k)]
norm_A_rev = np.max([norm(x_set[i])/norm(b_set[i]) for i in range(k)])
norm_A = norm(A, ord=np.inf)
print(norm_A*norm_A_rev, cond(A))

[31  0  0  0  0]
[ 0 43  0  0  0]
[ 0  0 19  0  0]
[ 0  0  0 65  0]
[ 0  0  0  0 50]
5.268311118453078 7.5435047


In [3]:
3.4
from scipy.linalg import lu_factor

lu, piv = lu_factor(A)

u = np.triu(lu)
l = np.tril(lu, k = -1) + np.eye(n)
print("L:\n",l)
print("U:\n",u)

b_new = np.linalg.inv(l)@b
print(b_new)

#решение нашей системы
x.reshape(7,1)

x_new = []
x_new.append(b_new[-1]/u[-1][-1])
for i in range (n-2, -1, -1):
    x_m = b_new[i] - np.dot(u[i][i+1:],x_new[-1::-1])
    x_m /= u[i][i]
    x_new.append(x_m)
    
solutions = np.array(x_new)
print("Решение, полученное обратным ходом:\n", solutions.reshape(7,1))
print("\nРешение, полученнное в пункте 3.1:\n",x.reshape(7,1))

L:
 [[ 1.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.05723906  1.          0.          0.          0.          0.
   0.        ]
 [ 0.15178571  0.33147321  1.          0.          0.          0.
   0.        ]
 [ 0.03320312 -0.43505859 -0.1640625   1.          0.          0.
   0.        ]
 [-0.04956268  0.2361516   0.1325452  -0.88363464  1.          0.
   0.        ]
 [ 0.0272     -0.19008    -0.0917504   0.58720256 -0.34233412  1.
   0.        ]
 [ 0.03935185 -0.21484375 -0.11437908  0.75079604 -0.68782645  0.79912378
   1.        ]]
U:
 [[-4.08496732e+00 -6.20039683e-01 -2.33819678e-01 -1.35633681e-01
  -1.11111111e-01 -1.60751029e-01  2.02461937e-01]
 [ 0.00000000e+00 -1.25260542e-01  2.69921707e-02  1.02752788e-02
   7.18294052e-03  9.55145745e-03 -1.14143446e-02]
 [ 0.00000000e+00  0.00000000e+00 -1.34207723e-01  5.10896955e-02
   2.14285714e-02  2.37453923e-02 -2.57969283e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.79612211e-02

In [31]:
3.5
n = 30
m = 9
A3 = np.empty([n, n])
b3 = [i**2 - 100 for i in range(n)]
b3 = np.array(b3)
for i in range(n):
    for j in range(n):
        if (i == j):
            A3[i][j] = n + m**2 + j/m + i/n
        else:
            A3[i][j] = (i+j)/(m+n)
            
L = np.linalg.cholesky(A3)
razl  = np.dot(L, L.T.conj())
#print("разложение матрицы А: ", razl)

y = np.linalg.solve(L,b3)
print("y = ",y)

x3 = np.linalg.solve(L.T.conj(), y)
print("x = ", x3)

new_x = np.linalg.solve(A3, b3)
print("nex x = ", new_x)

y =  [-9.49157996 -9.38836529 -9.08921376 -8.59486765 -7.90638557 -7.02513453
 -5.9527797  -4.69127212 -3.24283442 -1.60994474  0.20468083  2.19810722
  4.3672004   6.70864834  9.21898248 11.8945997  14.73178441 17.72673054
 20.87556334 24.17436063 27.61917352 31.20604626 34.93103517 38.79022664
 42.77975382 46.8958123  51.13467438 55.49270219 59.96635936 64.55222151]
x =  [-1.15589719 -1.1546237  -1.13536451 -1.09816481 -1.04306961 -0.97012379
 -0.87937207 -0.77085901 -0.64462904 -0.50072644 -0.33919533 -0.16007969
  0.03657663  0.25072996  0.48233674  0.73135359  0.99773724  1.28144457
  1.58243263  1.90065857  2.23607973  2.58865354  2.9583376   3.34508965
  3.74886756  4.16962934  4.60733314  5.06193725  5.53340009  6.02168022]
nex x =  [-1.15589719 -1.1546237  -1.13536451 -1.09816481 -1.04306961 -0.97012379
 -0.87937207 -0.77085901 -0.64462904 -0.50072644 -0.33919533 -0.16007969
  0.03657663  0.25072996  0.48233674  0.73135359  0.99773724  1.28144457
  1.58243263  1.90065857  2.23

In [33]:
3.6
import math 

M=6
m=6 #округление до 6 знаков после запятой
n=100 #порядок
t1=0.0001
t2=1
t3=10000

def gauss (A,b): #функция для метода Гаусса
    M=copy.copy(A) 
    s=copy.copy(b)
    x=np.zeros(n)
    
    #прямой ход
    for j in range(n):
        for i in range(j+1,n):
            mu=M[i,j]/M[j,j] #коэффициент
            M[i]-=M[j]*mu 
            s[i]-=s[j]*mu
            
    #обратный ход        
    x[n-1]=s[n-1]/M[n-1,n-1]
    
    for j in range(n-2,-1,-1):
        l=0
        for i in range(n-1-j):
            l+=(x[n-1-i]*M[j,n-1-i])
        x[j]=(s[j]-l)/M[j,j]
    return(x)

#вычисляем q по заданной формуле
q=0.993+((-1)**M)*(10**(-4))*M

#Вычислим три матрицы А для разных значений t
A_1=np.zeros([n,n])
A_2=np.zeros([n,n])
A_3=np.zeros([n,n])
for i in range(100):
    for j in range(100):
        if i!=j:
            A_1[i,j]=q**j
            A_2[i,j]=q**j
            A_3[i,j]=q**j
        else:
            A_1[i,j]=q**j+t1
            A_2[i,j]=q**j+t2
            A_3[i,j]=q**j+t3
#вычисляем вектор b по заданной формуле
b=np.zeros(n)
for j in range(n):
    b[j]=q**(n+1-j)
    
#решаем системы методом Гаусса
x_1=gauss(A_1,b)
x_2=gauss(A_2,b)
x_3=gauss(A_3,b)

#функция, округляющая число до заданной точности m 
def roundm(x):
        d = 10.0**m
        return math.floor(x*d)/d
    
#вычислим аналогично три матрицы А с округлением
A1_1=np.zeros([n,n])
A1_2=np.zeros([n,n])
A1_3=np.zeros([n,n])
for i in range(100):
    for j in range(100):
        if i!=j:
            A1_1[i,j]=roundm(q**j)
            A1_2[i,j]=roundm(q**j)
            A1_3[i,j]=roundm(q**j)
        else:
            A1_1[i,j]=roundm(q**j+t1)
            A1_2[i,j]=roundm(q**j+t2)
            A1_3[i,j]=roundm(q**j+t3)
#вектор b с округлением
b1=np.zeros(n)
for j in range(n):
    b1[j]=roundm(q**(n+1-j))
#решим полученные системы методом Гаусса    
x1_1=gauss(A1_1,b1)
x1_2=gauss(A1_2,b1)
x1_3=gauss(A1_3,b1)

#посчитаем погрешности как норму разности между полученными решениями с округлением и без округления
e1=np.linalg.norm(x_1-x1_1)
print(e1)
e2=np.linalg.norm(x_2-x1_2)
print(e2)
e3=np.linalg.norm(x_3-x1_3)
print(e3)
#чем больше величина t, тем меньше значение погрешности

0.030302822211248116
3.0297912444046617e-06
5.769026829970399e-10


In [25]:
3.7
import matplotlib.pyplot as plt

def lu_factorizer(A):
    shape = A.shape[0]
    l, u = np.eye(shape).astype('float64'), A.copy().astype('float64')
    pivot = np.zeros(shape)
    for i in range(shape):
        row, maxelem = i, np.abs(u[i,i])
        for k in range(i+1,shape):
            if (np.abs(u[k,i]) > maxelem):
                maxelem = np.abs(u[k,i])
                row = k
        pivot[i] = row
        for k in range(i,shape):
            temp = u[i,k]
            u[i,k] = u[row,k]
            u[row,k] = temp
        for k in range(i+1,shape):
            g = u[k,i] / u[i,i]
            l[k,i] = g
            for j in range(i, shape):
                u[k,j] -= g * u[i,j]        
    return l, u, pivot

def test(A):
    eps = 1e-12
    l, u, p = lu_factorizer(A)
    np_lu, p = lu_factor(A)
    lu = u + np.tril(l, k=-1)
    if np.abs(np.linalg.norm(l @ u,ord=np.inf) - np.linalg.norm(A, ord=np.inf)) < eps:
        return True
    else:
        return False
    
n=np.arange(2,150)
for m in n:
    C, A = np.ones((m,m)).astype('float64'), np.ones((m,m)).astype('float64')
    for i in range(m):
        for j in range(m):
            C[i][j] = 2.2 * (i + 1) * (j + 1)
            A[i][j] = 150 / (13 * C[i][j] ** 3 + 777 * C[i][j])
    if(not test(A)):
        print('Test ', m,' failed')
        
cond_list=[]
n=np.arange(2,100)
for m in n:
    C, A = np.ones((m,m)), np.ones((m,m))
    for i in range(m):
        for j in range(m):
            C[i][j] = 2.2 * (i + 1) * (j + 1)
            A[i][j] = 150 / (13 * C[i][j] ** 3 + 777 * C[i][j])
    l, u, p = lu_factorizer(A)
    Ainv = np.linalg.solve(u,np.linalg.solve(l, np.eye(l.shape[0])))
    cond = np.linalg.norm(Ainv, np.inf) * np.linalg.norm(A, np.inf)
    cond_list.append(cond)

plt.plot(n,np.log(cond_list))
plt.xlabel('N')
plt.ylabel('log scale cond num');

In [23]:
3.9
def chol(a):
  
  
    a = copy.deepcopy(a)
    
    m=a.shape[0]
    

    a[0, 0] = np.sqrt(a[0, 0])
    for i in range(1, m):
        a[i, 0] = a[i, 0] / a[0, 0]
     
    for k in range(1, m-1):
        a[k, k] = (a[k, k] - sum([a[k, q]**2 for q in range(0, k)]))**0.5
        for i in range(k+1, m):
            a[i, k] = (a[i, k] - sum([a[i, q]*a[k, q] for q in range(0, k)]))/a[k, k]
          
    a[m-1, m-1] = (a[m-1, m-1] - sum([a[m-1, q]**2 for q in range(0, m-1)]))**0.5
    
    for i in range(m):
        for j in range(i+1, m):
            a[i, j] = 0

    return a

n=20
m=8
def Aij(i, j, m=m, n=n):
    if i == j:
        return n + m**2 + j/m + i/n
    else:
        return (i+j)/(m+n)
def bi(i):
    return 200 + 50*i

A = np.array([[Aij(i, j) for i in range(1, n+1)] for j in range(1, n+1)]).reshape(n, n)
b = np.array([bi(i) for i in range(1, n+1)])
L = chol(A)
LT = L.T
y = solve(L, b)
x = solve(LT, y)

print(x, cond(A))

norm_A_rev = norm(x, ord=np.inf)/norm(b, ord=np.inf)
norm_A = norm(A, ord=np.inf)

print(norm_A*norm_A_rev)

[ 2.13216095  2.6630651   3.19266488  3.72096508  4.24797048  4.77368584
  5.29811588  5.82126532  6.34313883  6.86374109  7.38307673  7.90115037
  8.4179666   8.93352999  9.4478451   9.96091645 10.47274855 10.98334589
 11.49271292 12.00085408] 1.214443547613888
1.0786481942801718


In [4]:
3.10
n = 35
b = [i * np.exp(22. / i) * np.sin(9. / i) for i in range(1, n + 1)]

A = 100 * np.eye(n, n) + np.eye(n, n, k = 1) + np.eye(n, n, k = 2) + np.eye(n, n, k = 3) + np.eye(n, n, k = -1)

for j in range(10):
    print(j,":")
    print(A[-j][:])
    
print(b)

nozero = []
nozero.append([100., 1., 1., 1.])
for i in range(1,n-3):
    nozero.append([1., 100., 1., 1., 1.])
nozero.append([1., 100., 1., 1.])
nozero.append([1., 100., 1.])
nozero.append([1., 100.])

print(nozero)

B = 100 * np.eye(n, n) + np.eye(n, n, k = 1) + np.eye(n, n, k = -1)
print(B)

num = []
num.append([100., 1.])
for i in range(1,n-1):
    num.append([1., 100., 1.])
num.append([1., 100.])
print(num)

#алгоритм для трехдиагональной матрицы
def Thomas_algorithm(nozero,b,n):
    beta = np.zeros(n)
    alpha = np.zeros(n)
    gamma = np.zeros(n)
    
    #вычисление коэффицентов прогонки
    beta[0] = -b[0] / nozero[0][0]
    alpha[0] = - nozero[0][1]/nozero[0][0]
    gamma[0] = nozero[0][0]
    
    for i in range(1,n-1):
        gamma[i] = nozero[i][1] + nozero[i][0]*alpha[i-1]
        alpha[i] = - nozero[i][2] / gamma[i]
        beta[i] = (b[i] - nozero[i][0] * beta[i-1]) / gamma[i]

    gamma[n-1] = nozero[n-1][1] + nozero[n-1][0] * alpha[n-2]
    beta[n-1] = (b[n-1] - nozero[n-1][0] * beta[n-2]) / gamma[n-1]

    #вычесление x
    x = []
    x.append(beta[n-1])
    k = 0
    for i in range(n-2,-1,-1):
        x_k = alpha[i] * x[k] + beta[i]
        k += 1
        x.append(x_k)
        
    return(np.array(x))

sol1 = np.linalg.solve(B,b)
print(sol1[-1::-1])

sol = Thomas_algorithm(nozero,b,n)

sol

0 :
[100.   1.   1.   1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.]
1 :
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   1. 100.]
2 :
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   1. 100.   1.]
3 :
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   1. 100.   1.   1.]
4 :
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   1. 100.   1.   1.   1.]
5 :
[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.

array([ 1.65224807e-01,  1.66542405e-01,  1.69733919e-01,  1.73169675e-01,
        1.76898927e-01,  1.80959765e-01,  1.85397250e-01,  1.90264803e-01,
        1.95626195e-01,  2.01558130e-01,  2.08153616e-01,  2.15526442e-01,
        2.23817169e-01,  2.33201276e-01,  2.43900402e-01,  2.56198108e-01,
        2.70462388e-01,  2.87178459e-01,  3.06997611e-01,  3.30811795e-01,
        3.59870759e-01,  3.95971903e-01,  4.41779313e-01,  5.01382563e-01,
        5.81323603e-01,  6.92592639e-01,  8.54771795e-01,  1.10533454e+00,
        1.52249303e+00,  2.28895825e+00,  3.72139024e+00,  2.21756955e+01,
       -1.45973801e+03,  1.46599567e+05, -1.47755545e+07])