In [16]:
import numpy as np

#Gauss
def bubble_max_row(m, k):
    ind = k + np.argmax(np.abs(m[k:, k]))
    if ind != k:
        m[k, :], m[ind, :] = np.copy(m[ind, :]), np.copy(m[k, :])


def solve_gauss(m):
    n = m.shape[0]
    for k in range(n - 1):
        bubble_max_row(m, k)
        for i in range(k + 1, n):
            frac = m[i, k] / m[k, k]
            m[i, :] -= m[k, :] * frac
    if is_singular(m):
        print('The system has infinite number of answers...')
        return
    x = np.matrix([0.0 for i in range(n)]).T
    for k in range(n - 1, -1, -1):
        x[k, 0] = (m[k, -1] - m[k, k:n] * x[k:n, 0]) / m[k, k]
    display_results(x)


def is_singular(m):
    return np.any(np.diag(m) == 0)

#solve_gauss(m)

NameError: name 'm' is not defined

In [ ]:
#Cholesky
def cholesky(A):
    L = np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range(i + 1):
            if i != j:
                L[i,j] = 1 / L[j,j] * (A[i,j] - np.dot(L[i], L[j]))
            else:
                L[i,i] = np.sqrt(A[i,i] - np.dot(L[i], L[i]))
    return L
#Another LU decomposition
def LU(A):
    m = np.zeros(a.shape)
    m = A.copy()
    n = m.shape[0]
    for i in range(n - 1):
        for j in range(i + 1, n):
            m[j, i+1:] -= m[i, i+1:] * m[j, i] / m[i, i]
        m[i+1:, i] = m[i+1:, i] / m[i, i]
    L = np.tril(m)
    np.fill_diagonal(L, 1)
    return L, np.triu(m)

In [15]:
from math import sqrt
from pprint import pprint
#QR-decomposition
import numpy as np
 
def qr(A):
    m, n = A.shape
    Q = np.eye(m)
    for i in range(n - (m == n)):
        H = np.eye(m)
        H[i:, i:] = make_householder(A[i:, i])
        Q = np.dot(Q, H)
        A = np.dot(H, A)
    return Q, A
 
def make_householder(a):
    v = a / (a[0] + np.copysign(np.linalg.norm(a), a[0]))
    v[0] = 1
    H = np.eye(a.shape[0])
    H -= (2 / np.dot(v, v)) * np.dot(v[:, None], v[None, :])
    return H

a = np.array(((
    (12, -51,   4),
    ( 6, 167, -68),
    (-4,  24, -41),
)))
 
q, r = qr(a)
print('q:\n', q.round(6))
print('r:\n', r.round(6))

q:
 [[-0.857143  0.394286  0.331429]
 [-0.428571 -0.902857 -0.034286]
 [ 0.285714 -0.171429  0.942857]]
r:
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.   -0.  -35.]]


In [ ]:
x = np.linalg.solve(A, b) #Gauss method
x = np.linalg.solve(np.linalg.cholesky(A).T, np.linalg.solve(np.linalg.cholesky(A), b)) #Cholesky method
Q, R = np.linalg.qr(A) #Compute the qr factorization of a matrix.